spring:
  application:
    name: GLHMCloud
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:file:./glhmcloud/database/db}
    driver-class-name: ${DATASOURCE_DRIVER:org.h2.Driver}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:123456}
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      path: /h2admin
      enabled: false
  profiles:
    active: secret

server:
  port: 8081

logging:
  config: classpath:logback-spring.xml

mqtt:
  client:
    ip: ${MQTT_IP:wh.korostudio.cn}
    port: ${MQTT_PORT:1883}
    name: ${MQTT_NAME:GLHMCloud-GL}
    client-id: ${MQTT_CLIENT_ID:GLHMCloud-GL}
    username: ${MQTT_USERNAME:glhmcloud}
    password: ${MQTT_PASSWORD:glhm2025}

springdoc:
  api-docs:
    path: /pub/api-docs
  swagger-ui:
    path: /pub/swagger-ui.html

sa-token:
  token-name: glhmauth
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true